version: '3.8'

services:
  python-api:
    build: ./python-api
    container_name: python-api
    ports:
      - "8000:8000"
    networks:
      - app-network

  nodejs-api:
    build: ./nodejs-api
    container_name: nodejs-api
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
